# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f0038490fdbaad33a9c94d8dacdecbcf30840f1de1e92b19754a98c6eb94be6698748b35d3c07756817b88b0f91bbba15958b1280d96b9978767e85dd74fce9

test:
  secret_key_base: a86010889b361f038d98f30b1bc4fc7b701904185f703fe6c572020c3e784d20bf61cc5b42f125d25c0de1a7046168eb72e8db00b0f2ac240a5cf0be6b5b37e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
